git:
  depth: 1

language: node_js
node_js:
  - 8.14.0

script:
  - yarn lint
  - yarn build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build
  on:
    branch: master

